### PR TITLE
trying a loading block

### PR DESCRIPTION
**Pull request by jnakaso**
## What

> Having some fun, trying a LoadingBlock

## Why Do

> A little more flexible

## Show Me
Screen Shot 2024-02-23 at 15 37 13

> Screenshot of your change, if applicable.

### CODE REVIEW

**Comment by mistyb01** [comment]
This looks really cool! Only issue is that I still notice a brief appearance of the 'no events/roles' section before the loading block appears

**Review by mistyb01 — COMMENTED** [review]
This looks really cool. Only issue is that I still experience a brief flicker of the 'no events/roles' message, right before the loading block

**Review by mistyb01 — APPROVED** [review]
This fixes the issue and the loading block is a nice UI touch, thanks a bunch Jeff! Let's merge this version

**Review by ybalenko — APPROVED** [review]
What an elegant solution, @jnakaso! Thank you.

**Pull request merged**
