### PR TITLE
polish events page

### PR DESCRIPTION
**Pull request by sierrakn**
## What

Polishing events page

I wasn't sure if we're using the feature branch or not, but this is based off of it.

## Future work

We should make some constants for sizes and spaces we use consistently throughout the app but I wanted to get this in separately

## Show Me

image

image

### CODE REVIEW

**Comment by santina** [comment]
Some build error happening with sx https://vercel.com/dev-openseattle/open-seattle-website/CqzKKaThAYSq7P49wRVUYLDuZDAe 
Although we should also fix the CI failure of the branch itself too
https://github.com/openseattle/open-seattle-website/pull/42

**Review by santina — CHANGES_REQUESTED** [review]
Hi Sierra could you address Kylie's comments in the sticky notes here https://www.figma.com/file/Qa1UC7cGLmEXbWXuRmgjpO/OS-Website-Annotations?type=whiteboard&node-id=136-244&t=R7Ic16ISjJQafpE5-0 
Also if you could list out the feature you change about the page it'd help with reviewing. Thanks!

**Comment by gussmith23** [comment]
@sierrakn did you address Santina's comments on this PR?

**Review by mistyb01 — APPROVED** [review]
Kylie's feedback has been addressed! I'll go ahead and merge.

**Pull request merged**
