### PR TITLE
Jeffn/Apply a common masthead to multiple pages

### PR DESCRIPTION
**Pull request by jnakaso**
## What

> Apply a common masthead to multiple pages

## Why Do

> Ensure consistency

## How Do

> Partners page should benefit from this as well.

### CODE REVIEW

**Comment by santina** [comment]
Nice! As a suggestion could we make the title of the PR something like *Apply a common masthead to multiple pages* it'll make the commit history more readable :)

**Comment by santina** [comment]
Have you also checked to make sure all the breakpoints work and doesn't break any polish work people have done before https://www.figma.com/file/Qa1UC7cGLmEXbWXuRmgjpO/OS-Website-Annotations?type=whiteboard&node-id=0-1&t=0wVmkW4pk8p4cGCa-0

**Comment by jnakaso** [comment]
> Nice! As a suggestion could we make the title of the PR something like _Apply a common masthead to multiple pages_ it'll make the commit history more readable :)

Done!

**Comment by jnakaso** [comment]
> Have you also checked to make sure all the breakpoints work and doesn't break any polish work people have done before https://www.figma.com/file/Qa1UC7cGLmEXbWXuRmgjpO/OS-Website-Annotations?type=whiteboard&node-id=0-1&t=0wVmkW4pk8p4cGCa-0

MastheadWithImage is derived from just extracting code that was duplicated across a number of pages.  Using a component is easier to maintain over cut&paste reuse.

**Review by santina — APPROVED** [review]
Thank you!

**Pull request merged**
