### PR TITLE
Added tag title

### PR DESCRIPTION
**Pull request by ybalenko**
## What

> Added page tag title

## Why Do

> Per designer's request [here](https://github.com/orgs/openseattle/projects/1/views/2?pane=issue&itemId=40514863)

## Show Me

> Checked it locally in 3 browsers: Chrome, Firefox and Safari.

Screenshot 2023-10-17 at 16 32 33

### CODE REVIEW

**Review by jnakaso — APPROVED** [review]
Woot

**Comment by mistyb01** [comment]
go ahead and merge! though we might want each page to have its own title

**Comment by jnakaso** [comment]
> go ahead and merge! though we might want each page to have its own title eventually

we can use something like this to get tag per pages:

`
  const DEFAULT_TAG = "Free tech solutions for Puget Sound nonprofits | Digital Aid Seattle";
  const tagNames = {
    'events': 'EVENT TAG TITLE',
    'volunteers': 'VOLUNTEER TAG TITLE'
  }
  const path = usePathname().split('/');
  const [title, setTitle] = useState(DEFAULT_TAG);
  useEffect(() => {
    const tag = tagNames[path[path.length - 1]];
    setTitle(tag ? tag : DEFAULT_TAG);
  }, [path])
`

**Comment by ybalenko** [comment]
It's no longer needed, closing.

**Pull request closed without merging**
